name: "CloudFlare DNSLink+"
description: "Create or update CloudFlare DNSLink and gateway"
author: "itera.one"

inputs:
  name:
    description: 'dnslink domain, e.q. my-awesome-website.itera.one'
    required: true
  cid:
    description: 'Ipfs CIDv0'
    required: true
  gateway:
    description: 'Ipfs gateway domain'
    required: false
  token:
    description: "CloudFlare API token"
    required: true
  zone:
    default: "CloudFlare zone"
    required: true
outputs:
  txt_record_id:
    description: "TXT record ID"
  txt_record_name:
    description: 'TXT affected domain name'
  cname_record_id:
    description: 'CNAME record ID'
  cname_record_name:
    description: 'CNAME affected domain name'
runs:
  using: "node12"
  main: "main.js"

branding:
  icon: "cloud"
  color: "orange"
